### ISSUE TITLE
能否增加一个鼠标停留时间的选项？避免鼠标划过时不必要的的的单词释义窗口popup?

### ISSUE THREAD

**Issue by HeroBlackInk** [word-hunter/word-hunter#120]
如果一个页面的生词太多，鼠标移动划过就会弹出释义。

能否增加选项，只有当鼠标在单词上停留超过一定时间，才会弹出解释？

可以用如下办法实现：当准备弹出释义窗口时候，增加100毫秒的延迟，然后检测鼠标是否停留在单词的位置。如果鼠标已经不在当前的位置，则不需要弹窗。

**Comment by sapjax** [comment]
You can choose a Control key in Settings:

![image](https://github.com/user-attachments/assets/974eecbd-f758-4e9b-9176-063bf4c751c4)
