### ISSUE TITLE
Google drive sync failed

### ISSUE THREAD

**Issue by CEX68** [word-hunter/word-hunter#25]
`Sync Failed: Cannot convert undefined or null to object`.
Reproduce
1. Backup with `Google Drive Sync`
2. Click `Google Drive Sync` again

**Comment by sapjax** [comment]
> `Sync Failed: Cannot convert undefined or null to object`. Reproduce

Can't reproduced, please upload the error info in DevTool console of the options page.

**Comment by CEX68** [comment]
I can not reproduce this error too now.

**Comment by sapjax** [comment]
Close because there is no more reproduction.
