### ISSUE TITLE
Can I export the saved context as a Txt file?

### ISSUE THREAD

**Issue by osgg** [word-hunter/word-hunter#65]
Can I  export the saved context as a Txt file?

**Comment by sapjax** [comment]
> Can I export the saved context as a Txt file?

You can click on the `export` button in settings page.
it will download the json file contains knowns word list and saved context, you can open the file via any text editor.

**Comment by osgg** [comment]
> > Can I export the saved context as a Txt file?
> 
> You can click on the `export` button in settings page. it will download the json file contains knowns word list and saved context, you can open the file via any text editor.



> > Can I export the saved context as a Txt file?
> 
> You can click on the `export` button in settings page. it will download the json file contains knowns word list and saved context, you can open the file via any text editor.

can you share a screenshot for the "export" button, as I didn't find it in the setting page

**Comment by sapjax** [comment]
> can you share a screenshot for the "export" button, as I didn't find it in the setting page

<img width="284" alt="image" src="https://github.com/word-hunter/word-hunter/assets/990255/4ed14b10-1cb8-49af-9efb-72879a82f9ea">

**Comment by osgg** [comment]
![image](https://github.com/word-hunter/word-hunter/assets/17079137/591375b8-8e96-4545-9c13-14391532744f)
Backup button can only save profile data excluding context data as you can see in the picture

**Comment by sapjax** [comment]
> Backup button can only save profile data excluding context data as you can see in the picture

No, that tooltip is for "automatically sync", not for manually backup.

**Comment by osgg** [comment]
Json format is not human-readable, it would be better if we could export the data as Txt or other human-readable formats

**Comment by sapjax** [comment]
> Json format is not human-readable, it would be better if we could export the data as Txt or other human-readable formats

Json is human-readable already, and you can write script to process it as you want.
