### ISSUE TITLE
有几点小建议反馈下

### ISSUE THREAD

**Issue by BulbLi** [word-hunter/word-hunter#71]
首先，感谢作者的开源，是很不错的项目。但是有几个小问题反馈下：

1. 添加单词到unknown不是太方便，需要额外右键，然后再选择添加。但是添加了以后，还是没有用？
2. 由于英文单词有多种释义，要是能对中文释义进行选择就好了。
3. 对于已认识的单词进行取消高亮后，发现中文释义还在？需要网页重新刷新后才消失。

**Comment by sapjax** [comment]
> 首先，感谢作者的开源，是很不错的项目。但是有几个小问题反馈下：
> 
> 1. 添加单词到unknown不是太方便，需要额外右键，然后再选择添加。但是添加了以后，还是没有用？
> 2. 由于英文单词有多种释义，要是能对中文释义进行选择就好了。
> 3. 对于已认识的单词进行取消高亮后，发现中文释义还在？需要网页重新刷新后才消失。

1. "Mark as unknown" 只是用于不小心标记成 known 的情况下“撤销”操作，并不是用于将一个词没有被高亮的词设置成高亮，如果一个词没有被高亮，它有两种可能：1. 单词没有被词典收录，2. 在设置里面没有打开对应的 level。
2. 鼠标悬浮到中文释义上会显示完整的释义，如果没有对应的释义，那就是收录不全
3. 这是有意的，为了避免排版变动，尤其是大段长文本的时候
