### ISSUE TITLE
FR: show Chinese translation only for the first word on the current webpage

### ISSUE THREAD

**Issue by pasiooooo** [word-hunter/word-hunter#77]
Chinese translation is very useful, but it also affects the layout, especially when there are a lot of repetitions of a certain word. Can you add an option or directly change it to only display the Chinese translation of the first word of the current web page?

**Comment by sapjax** [comment]
Do you mean only show translation once for each word?

**Comment by pasiooooo** [comment]
Correct, that's it.

**Comment by pasiooooo** [comment]
> Do you mean only show translation once for each word?

Correct, that's it.

**Comment by sapjax** [comment]
That make sense, will do it in next release.
