### ISSUE TITLE
Add shortcuts for unfamiliar word

### ISSUE THREAD

**Issue by yidongnan** [word-hunter/word-hunter#79]
<img width="725" alt="image" src="https://github.com/user-attachments/assets/f45bf2f1-f982-4cd2-85bf-c060cb800312">

This is a great plugin, thank you very much.

I encountered a problem while using it. If there are many unfamiliar words, I hope to quickly mark them using some shortcuts. For example, when I select the Chinese translation with the mouse, I hope to quickly mark the unfamiliar words by right-clicking or middle-clicking the mouse.

**Comment by sapjax** [comment]
You can move the mouse onto the word itself, then press `A` key to mark it as known, or `S` key to save the context.
Will also make it work on the translation in next release.
