### ISSUE TITLE
FR: Disable on this site 域名匹配设置

### ISSUE THREAD

**Issue by hazykam** [word-hunter/word-hunter#81]
当启用 Disable on this site 时，跳转到二级域名相同，但三级域名不同的页面时，禁用未生效，需要再次禁用。
例如：www.bilibili.com / live.bilibili.com

希望可以使用 DOMAIN-KEYWORD 类似的规则来进行匹配，或增加可以手动设置的域名匹配选项。

**Comment by sapjax** [comment]
这个操作不太常用，暂时不想增加交互界面去做，一般来说三级域名应该不会太多，可以一个个点过去手动禁用。

**Comment by sapjax** [comment]
在新的 1.1.13 版本中，我们调整了域名的匹配规则，父域名可以匹配任意子域名，
比如: bilibili.com 可以匹配 www.bilibili.com 和 live.bilibili.com
但是我们暂时没有添加手动编辑的界面，你可以在 Google Drive 中直接编辑 backup 文件中的 blacklist 中的域名列表，或者下载 backup，再 restore 回去。
